// <auto-generated />
using System;
using Fiap.Api.Donation1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Api.Donation1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SugestaoTroca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("DataCadastro");

                    b.HasIndex("TipoProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9866),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9867),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 1",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 2,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9878),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9878),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 2",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 3,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9881),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9882),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 3",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 4,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9885),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9886),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 4",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 5,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9888),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9889),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 5",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 6,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9892),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9893),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 6",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 7,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9974),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9974),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 7",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 8,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9978),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9978),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 8",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 9,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9981),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9982),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 9",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 10,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9984),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9985),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 10",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 11,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9987),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9988),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 11",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 12,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9990),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9991),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 12",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 13,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9993),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9994),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 13",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 14,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9996),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9997),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 14",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 15,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 513, DateTimeKind.Local).AddTicks(9999),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 15",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 16,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(3),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(3),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 16",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 17,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(6),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(7),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 17",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 18,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(9),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(9),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 18",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 19,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(12),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(13),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 19",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 20,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(15),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(16),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 20",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 21,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(18),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(19),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 21",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 22,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(21),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(22),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 22",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 23,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(24),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(25),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 23",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 24,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(27),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(28),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 24",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 25,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(31),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(32),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 25",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 26,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(34),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(35),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 26",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 27,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(37),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(38),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 27",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 28,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(40),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(41),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 28",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 29,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(43),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(44),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 29",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 30,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(46),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(47),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 30",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        },
                        new
                        {
                            ProdutoId = 31,
                            DataCadastro = new DateTime(2023, 10, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(49),
                            DataExpiracao = new DateTime(2025, 4, 18, 20, 58, 7, 514, DateTimeKind.Local).AddTicks(50),
                            Descricao = "Descrição",
                            Disponivel = true,
                            Nome = "Produto 31",
                            SugestaoTroca = "Sugestão de troca",
                            TipoProdutoId = 1,
                            UsuarioId = 1,
                            Valor = 1.0
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.TipoProdutoModel", b =>
                {
                    b.Property<int>("TipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoProdutoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("TipoProdutoId");

                    b.ToTable("TipoProduto");

                    b.HasData(
                        new
                        {
                            TipoProdutoId = 1,
                            Descricao = "Descrição para celular",
                            Nome = "Celular"
                        },
                        new
                        {
                            TipoProdutoId = 2,
                            Descricao = "Descrição para TV",
                            Nome = "TVs"
                        },
                        new
                        {
                            TipoProdutoId = 3,
                            Descricao = "Descrição para ar-condicionado",
                            Nome = "Ar-condicionado"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.TrocaModel", b =>
                {
                    b.Property<Guid>("TrocaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProdutoId1")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId2")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TrocaId");

                    b.HasIndex("ProdutoId1");

                    b.HasIndex("ProdutoId2");

                    b.ToTable("Troca");
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Regra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            EmailUsuario = "sa@fiap.com.br",
                            NomeUsuario = "Super Admin",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 2,
                            EmailUsuario = "fmoreni@fiap.com.br",
                            NomeUsuario = "Flavio Moreni",
                            Regra = "admin",
                            Senha = "123456"
                        },
                        new
                        {
                            UsuarioId = 3,
                            EmailUsuario = "emoreni@fiap.com.br",
                            NomeUsuario = "Eduardo Moreni",
                            Regra = "admin",
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.ProdutoModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation1.Models.TipoProdutoModel", "TipoProduto")
                        .WithMany()
                        .HasForeignKey("TipoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation1.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoProduto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fiap.Api.Donation1.Models.TrocaModel", b =>
                {
                    b.HasOne("Fiap.Api.Donation1.Models.ProdutoModel", "ProdutoModel1")
                        .WithMany()
                        .HasForeignKey("ProdutoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Api.Donation1.Models.ProdutoModel", "ProdutoModel2")
                        .WithMany()
                        .HasForeignKey("ProdutoId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoModel1");

                    b.Navigation("ProdutoModel2");
                });
#pragma warning restore 612, 618
        }
    }
}
